Milestone2
arikarim/Calculator pull request #3
Opened 2021-05-14 19:43 UTC by arikarim

In this milestone, I added all the necessary components and buttons for the calculator and added some simple styling.

2021-05-14 20:40 UTC, Forison requested changes
#### Status::Changes Required❌ 

# 👋 @arikarim 

#### You have done a good job on this one so far, You created the desired directory and all the component needed for this milestone, however here are some issues we have to address to get this project approved😇.

* [x] Your pull request should made up of a title and a short description of what you did specifically on this branch, this very important when working in a team 
([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)).

 * [x] App.js has children components wrapped in React.Fragment short syntax ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone2/app/ReactFragment.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/44896092/)), The use of react fragment prevent you from creating node that otherwise you create for the sake of the react convention. This helps you write more efficient code.

 * [ ] In Display.jsx, the result prop should be a String with default value = 0 ([should be String screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone2/display/validateAsString.png)) ([default props screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone2/display/DefaultProp.png))
Currently, running typeof on the default results returns a number, let return a string instaed.

#### That is it, kindly make the change and submit a re-review🏌️‍♀️.

#### Happy coding👨‍💻

Addo Forison

2021-05-14 20:40 UTC, Forison commented on src/components/App.js
> +  <div className="">
Use React fragment`<></>`, as required to avoid "unwanted" node creation for efficiency.

2021-05-14 20:40 UTC, Forison commented on src/components/Display.js
> +  result: 0,
result: '0'

2021-05-15 20:12 UTC, Forison requested changes
## Change Required❌

### Good job on changing the default value of result to string👏👏👏. Check my comment below on how it has to be.

- Kindly make the change and submit for a re-review.

Happy coding

2021-05-15 20:12 UTC, Forison commented on src/components/App.js
> +  <div className="col-2 mx-auto">
```
<>

<Display />

<ButtonPanel />

</>
```
React requires you to return all elements in one node so sometimes we create nodes that are not wanted, this requirement seeks to let you know the importance of [React Fragment](https://reactjs.org/docs/fragments.html).

2021-05-15 23:14 UTC, addod19 approved these changes
## Status: Approved :trophy: :balloon: 

Hi @arikarim, congratulations on this milestone :+1: The child components in the App.js file have been wrapped with React.Fragment short syntax as outlined by the previous reviewer :1st_place_medal: 

I hereby approve the project :smile: 
Do not forget to submit the project completion form :slightly_smiling_face: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2021-05-15 23:21 UTC, merged